[package]
name = "nttp-rust"
version = "0.1.0"
authors = ["alan20210202 <little_alanma@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
rand = "0.7.3"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.1"
bytes = "0.5.6"
pin-project-lite = "0.1.7"
pnet = "0.26.0"
winapi = { version = "0.3.9", features = [ "winsock2", "ws2ipdef", "mstcpip", "iphlpapi", "heapapi", "ipmib" ] }
log = "0.4.0"
simple_logger = "1.9.0"
once_cell = "1.4.1"
crossbeam = "0.7.3"

[build-dependencies]
cc = "1.0.59"



