[package]
name = "nttp-rust"
version = "0.1.0"
authors = ["alan20210202 <little_alanma@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tokio = { version = "0.2", features = ["full"] }
# rand = "0.7.3"
# bincode = "1.3.1"
# pin-project-lite = "0.1.7"
serde = { version = "1.0.115", features = ["derive"] }
# serde_json = "1.0"
toml = "0.5.6"
bytes = "0.5.6"
pnet = "0.26.0"
winapi = { version = "0.3.9", features = [ "winsock2", "ws2ipdef", "mstcpip", "iphlpapi", "heapapi", "ipmib", "ifdef" ] }
log = "0.4.0"
simple_logger = "1.9.0"
once_cell = "1.4.1"
lazy_static = "1.4.0"
crossbeam-utils = "0.7.2"
crossbeam-channel = "0.4.4"

[build-dependencies]
env_logger = "0.7.1"
cc = "1.0.59"
bindgen = "0.55.1"



