[package]
name = "nttp-rust"
version = "0.1.0"
authors = ["alan20210202 <little_alanma@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
rand = "0.7.3"
serde = "1.0.115"
bincode = "1.3.1"
bytes = "0.5.6"
pin-project-lite = "0.1.7"
pnet = "0.26.0"

[profile.release]
debug = true

